binance_api_tickerPrice_url: https://api.binance.com/api/v3/ticker/price
binance_api_24h_tickerPrice_url: https://api.binance.com/api/v3/ticker/24hr
binance_api_exchangeInfo_url: https://api.binance.com/api/v3/exchangeInfo
binance_api_avgPrice_url: https://api.binance.com/api/v3/avgPrice
binance_api_convertible_url: https://api.binance.com/sapi/v1/convert/exchangeInfo
spring:
 output:
  ansi:
   enabled: always
 jpa:
  open-in-view: true
 profiles:
  active: remote
server:
 port: 8080