bot:
 name: crypto_currencies_pet_bot
 token: 6486827539:AAE9T7PE2VVJvdEctTrtcMj0nCkuDczErl0
binance:
 api:
  tickerPrice:
   url: https://api.binance.com/api/v3/ticker/price
  exchangeInfo:
   url: https://api.binance.com/api/v3/exchangeInfo
  avgPrice:
   url: https://api.binance.com/api/v3/avgPrice
  convertible:
   url: https://api.binance.com/sapi/v1/convert/exchangeInfo
spring:
 output:
  ansi:
   enabled: always
 jpa:
  open-in-view: true
 profiles:
  active: remote
server:
 port: 8080