spring:
  datasource:
    password: ${elephant_db_password}
    url: jdbc:postgresql://hattie.db.elephantsql.com:5432/
    username: ucivlcsx
    driver-classname: org.postgresql.Driver
  output:
      ansi:
        enabled: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      #schema-locations: classpath:/schema.sql
      continue-on-error: true
  config:
    activate:
      on-profile: deploy
bot:
  name: ${bot_name}
  token: ${bot_token}