bot_name: crypto_currencies_pet_bot
bot_token: 6486827539:AAE9T7PE2VVJvdEctTrtcMj0nCkuDczErl0
binance_api_tickerPrice_url: https://api.binance.com/api/v3/ticker/price
binance_api_exchangeInfo_url: https://api.binance.com/api/v3/exchangeInfo
binance_api_avgPrice_url: https://api.binance.com/api/v3/avgPrice
binance_api_convertible_url: https://api.binance.com/sapi/v1/convert/exchangeInfo
spring:
 output:
  ansi:
   enabled: always
 jpa:
  open-in-view: true
 profiles:
  active: container
server:
 port: 8080